### PR TITLE
Add TOC to README.

### LINKED ISSUE #101: Add TOC to README
Related: #95, #102

### PR DESCRIPTION
**Pull request by ryan-roemer**
* Add auto-TOC to README. FIxes #101 
* Add Node 5.7 to Travis build matrix.

/cc @coopy

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@paulathevalley -- Also appreciate your review to make sure that this won't mess up the landers that work off this raw content (?)

**Comment by paulathevalley** [comment]
@ryan-roemer Spectacle has a TOC in its readme, too, so this is how it will look: http://formidable.com/open-source/spectacle/ 

Ideally, for a single `README.md`, the lander would pull this TOC out of the `README.md` and put it in a sidebar. I looked into it a little bit but didn't find an obvious solution. The `<ul>` element doesn't have an `id` like the headings do nor a way to add one to an element that's not an anchor (in markdown). 

One alternative would be to create a `/docs` folder and start splitting up the `README.md` into separate sections. [Radium does this](https://github.com/FormidableLabs/radium/tree/master/docs), which will allow the lander to create routes for each section. Instead of a single page, there would be a couple pages.

Let me know what you think makes the most sense for builder in terms of maintaining the markdown docs. I'm happy to investigate pulling the sidebar out or help wrangle some `/docs` sections.

**Comment by coopy** [comment]
The Builder README is large enough to warrant splitting it up into multiple pages.

**Comment by ryan-roemer** [comment]
@coopy how about future ticket? I'm implementing a ticket of yours already here ;)

@paulathevalley does it break the existing landers?  If it's just a future optimization I can help you with a good selector or maybe some other hack to make the table of contents extractable for your use.

**Comment by coopy** [comment]
@ryan-roemer yeah definitely future ticket - I was commenting on Paula's suggestion.
This change looks good if we can make it work acceptably for the builder lander page. That to me could be a top-of-page TOC to start, with a side bar as a second phase and possibly splitting up into multiple pages later. However, a side bar with anchors to all the headings on a single page works almost as well as multi-pages navigation.

**Comment by paulathevalley** [comment]
@ryan-roemer No, it will not break the existing landers. 

Although, @kylecesmat just ran into an issue where punctuation in headings will insert extra hypens into the links. A handful of the links in builder have backticks or `?`, so those links may (or may not) be broken. This something we will need to fix across the board. https://github.com/FormidableLabs/radium-docs/issues/12  

The TOC at the top of the page will still be a great start.

**Comment by ryan-roemer** [comment]
Sounds good! Thanks for the review @paulathevalley and @coopy !

**Pull request merged**
