### PR TITLE
BUG: isBuilderTask doesn't correctly infer on Windows.

### LINKED ISSUE #138: BUG: `isBuilderTask` does not do correct inference on Windows.
Hi, it seems that builder spawns many processes and fails on Windows 10. 
C:\Projects\sdmp-ui>builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:13292] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:9136] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:14356] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:8972] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:16160] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:10168] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:8224] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:1900] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:7816] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:10072] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:2572] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:4856] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:15528] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:8392] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:10048] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:10132] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:10224] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:15600] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:2056] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:11964] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:5212] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:15328] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:5088] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:7100] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:16300] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:7376] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:3984] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:2532] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:7316] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:928] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:14256] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:8756] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
[builder:config:environment] {"cwd":"C:\\Projects\\sdmp-ui","dir":"C:\\Projects\\sdmp-ui\\node_modules\\builder\\lib"}
[builder:builder-core:start:15728] Started: run build
[builder:run] build - builder run build
[builder:proc:start] Command: builder run build
'builder' is not recognized as an internal or external command,
operable program or batch file.
[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:15728] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:8756] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:14256] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:928] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:7316] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:2532] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:3984] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:7376] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:16300] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:7100] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:5088] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:15328] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:5212] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:11964] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:2056] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:15600] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:10224] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:10132] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:10048] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:8392] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:15528] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:4856] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:2572] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:10072] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:7816] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:1900] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:8224] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:10168] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:16160] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:8972] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:14356] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:9136] Task: run build, Error: Command failed: cmd /d /s /c builder run build

[builder:proc:end:1] Command: builder run build
[builder:builder-core:end:13292] Task: run build, Error: Command failed: cmd /d /s /c builder run build

Node: v6.2.2
Npm: 4.4.4

### PR DESCRIPTION
**Pull request by ryan-roemer**
Confusingly lots of stuff here...

- **Actual issue**: Fix builder passthrough determination on Windows. This is just @GEMI 's fix from #139 that I've copied with lots of other stuff going on. Fixes #138 
- Travis CI fails weirdly from an istanbul / node-mkdirp issue on Node 6's somewhere by `6.10.2`. I've captured the issue in a ticket and just pinned `6.9.2`
- I've honed down the `.npmignore` to make the package smaller.
- Removed npm@2 from testing on Node 5 and 6.

/cc @GEMI

### CODE REVIEW

**Comment by ryan-roemer** [comment]
CI failures in node6 may be related to: https://github.com/substack/node-mkdirp/pull/110

**Comment by ryan-roemer** [comment]
@GEMI -- I've got a replacement for your #139 PR because there was a lot of totally unrelated stuff it took to make travis happy. Can you pull down the PR and make sure it still works for you?

I've added attribution to you for `HISTORY.md`, but if I merge this PR you won't actually have commit history attribution because I copied and pasted -- is that OK?

Thanks!

**Comment by GEMI** [comment]
Sure do whatever you want. It's your project :)

**Comment by ryan-roemer** [comment]
Released in `builder@3.2.2`

**Pull request merged**
