### PR TITLE
Readme: Use smart quotes instead of dumb quotes

### PR DESCRIPTION
**Pull request by paulathevalley**
Replaces all the prime marks (to be read as ' feet or " inches) with smart quotes! Yay, smart quotes. This will make us look smart and the lander page read beautifully.

To read more about smart quotes: http://smartquotesforsmartpeople.com/ 

/cc @david-davidson @coopy

### CODE REVIEW

**Comment by david-davidson** [comment]
Looks good! Double-checked the rendered HTML to make sure we didn't interfere with any code. :+1: 

Any objections, @ryan-roemer?

**Comment by ryan-roemer** [comment]
Smart quotes are bad for code, text editors and markdown. Prefer we don't change source like this for any of or md files.

Is there some way when ingested into final builder-docs site we can transform _then_?

**Comment by ryan-roemer** [comment]
E.g., something like https://github.com/kellym/smartquotesjs but maybe more "React-friendly"?

**Comment by zachhale** [comment]
I'll also cast my vote for not changing the markdown files to use smart quotes. There's no good way to enforce these and it's difficult to ensure correct usage for the reasons @ryan-roemer mentioned.

**Comment by david-davidson** [comment]
@ryan-roemer @zachhale Makes sense--we'll tackle transforming them (if we do so at all) on the consuming side.

**Comment by exogen** [comment]
I think it's worth checking out an automatic transform. FWIW though I'm of the opinion that smart quotes belong in the authoring step like Paula is doing. I use smart-quotes in some of my repos (docs, interactive CLI prompts/output) – it's fine. `script-atomic-onload`'s README is all smart quotes, for example. If someone writes some new markdown and forgets to use them, no biggie – treat it like some wording that could be improved and catch it later.

**Comment by ryan-roemer** [comment]
Closing here so we can keep straight quotes and leaving it to upstream consumption to "smartenize".

@paulathevalley Can you delete the branch if you're OK with that?

Thanks!

**Pull request closed without merging**
